### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NeoSlugman** [loulasedna/Resawod_nubapp#1]
Bonjour,

Ton script est-il fonctionnel ?
J'ai tenté de le lancer avec les paramètres -e (account) et -p (password)  mais sans succès.

J'ai ce retour : 
```
[moncompte@gmail.com] Running script on 2023-11-10 13:43:45.744238
Traceback (most recent call last):
  File "/home/moi/./book.py", line 181, in <module>
    main(options.account, options.password)
  File "/home/moi/./book.py", line 139, in main
    id_application = res_login.get('resasocialAccountData').get('boundApplicationData').get('monIDdeBox')
AttributeError: 'NoneType' object has no attribute 'get'
```

Merci

**Comment by loulasedna** [comment]
hello oui, je l'utilise chaque semaine. il faut cependant que tu modifies 2 chose à l'intérieur du script 
la première est cette ligne sess_id = get_session_id(session, '21891030'). le chiffre correspond à ta box. Regarde dans les échanges réseau quand tu réserve depuis ton pc (mode expert) , tu devrais voir passer quelque chose en ce sens : https://sport.nubapp.com/web/setApplication.php?id_application=21891030 par exemple crossit versailles : https://www.crossfit-versailles.com/reservations si tu veux tester

Ensuite n'hésites pas à modifier les heures et jours de réservation, ce sont ces deux lignes
    days = [ ('tuesday', 1), ('wednesday', 2), ('thursday', 3)]
[...]
        eligible_slots= [s for s in slots if '18:30:00' in s['start']]

voilà :) 

Enjoy !

**Comment by NeoSlugman** [comment]
Je vais tester ça et je cloturerai le ticket si c'est tout bon.

J'avais fait la modif pour l'ID de la box, mais pas pour les créneaux. Mais comme on est samedi, je n'ai pas les créneaux de la semaine prochaine. Je regarderai le contenu du JSON dimanche soir quand ça va ouvrir.

Ce qui est rigolo, c'est que je dois passer faire un drop in à Versailles après avoir testé HATI il y a 2 semaines 😄

**Comment by NeoSlugman** [comment]
J'ai trouvé le souci : 
Le 'resasocialAccountData' a pour valeur 'None' dans mon JSON. Il n'arrive donc pas à faire le get.
ChatGPT m'a fait faire des tests et quelques modifs. Ca a fonctionnné et j'ai (accidentellement) réservé tous les créneaux de la semaine à 18:30 😄 

J'avais aussi un souci car la variable 'id_category_activity' n'avait pas la même valeur dans ma box.

Je vais continuer dans cette voie et certainement passer quelques éléments en variable, comme l'heure du créneau.

Ca t'intéresse que je te propose une/des PR ou je forke et je fais les modifs de mon coté ?

**Comment by loulasedna** [comment]
Hello.

Si ça te dis, fais une PR avec les nouvelles variables :)

**Comment by NeoSlugman** [comment]
Je t'ai fait une PR avec la doc qui va avec ;)
